### ISSUE TITLE
Examples syntax changes

### ISSUE THREAD

**Issue by kleinash** [dmlc/MXNet.jl#80] opened 2016-04-15 07:49 UTC
Hi, 

**Julia v 0.4.5; MXNet 0.0.8** 

I am trying to train a CNN model, save the model, test the model and then use it again so load the model. 

When looking at your examples I find that I cannot run as is, with my data - the error is that it does not find `@test` so pointing to the repository this line seems to have changed:
https://github.com/dmlc/MXNet.jl/blob/master/examples/mnist/mlp-test.jl#L41 (`mlp_load = mx.load("$cp_prefix-symbol.json", mx.SymbolicNode)`)
It works when I change it to this: 
`model_load = mx.load_checkpoint(joinpath("./eval/","$cp_prefix"), 0001) # if you want to load the 0001 epoch`

The second line that has changed is this one: 
`@test mx.to_json(model_load) == mx.to_json(net)`
https://github.com/dmlc/MXNet.jl/blob/master/examples/mnist/mlp-test.jl#L42
But I haven't figured out what is should be **I get this error**:
> ERROR: LoadError: MethodError: `to_json` has no method matching to_json(::Tuple{MXNet.mx.SymbolicNode,Dict{Symbol,MXNet.mx.NDArray},Dict{Symbol,MXNet.mx.NDArray}})

Sorry to be such a noob - but how do I fix this? 

Thx

**Comment by pluskid** [comment] 2016-04-18 15:37
Sorry I do not quite understand your question. Can you describe what you did, what is the expected behavior and what is the (unexpected) results you get instead? Thanks!

**Comment by vchuravy** [comment] 2016-04-19 02:15
@kleinash When posting Julia code always surround it with ``` 
especially when mentioning macros since the @ syntax conflicts with user names and you thus ping the user `@test` on github.

Also always post the version of Julia and MXNet/MXnet.jl you are using :)

**Comment by kleinash** [comment] 2016-04-19 06:29
@pluskid please see updated version - does that help?
@vchuravy Thanks for the heads up - will keep this in mind for future.

**Comment by vchuravy** [comment] 2016-04-19 06:42
@kleinash What are you trying to do? It seems you have a model trained and you now want to use it for prediction?

```
data = ... # Some instance of DataProvider 
model =  mx.load_checkpoint(joinpath("./eval/","$cp_prefix"), 1)
pred = mx.predict(model, data)
```

The error you are getting indicates that the value you are providing to `mx.to_json` is of the wrong type. Check the types of the variables with `typeof`.

**Comment by kleinash** [comment] 2016-04-19 07:38
@vchuravy Will do - However I am a little behind - dealing with this error:

ERROR: LoadError: AssertionError: get_batch_size(opts.eval_data) == batch_size

as soon as I try and find my validation error - which is in another issue. #64

**Comment by kleinash** [comment] 2016-04-19 18:07
Not sure what happened, but I updated, checked out etc. and it's all working finally. I don't have any errors or memory errors not a clue but thanks for any time at all you have to read and answer this.

Now I can get on with. Would love to know what or how it was sorted out but have to get on to hyperparamaters. Should I close this?

**Comment by pluskid** [comment] 2016-04-20 13:38
Great! I'm closing this. Feel free to re-open if needed.

**Closed by pluskid** 2016-04-20 13:38 UTC
