### ISSUE TITLE
regression-example.jl fail

### ISSUE THREAD

**Issue by Balinus** [dmlc/MXNet.jl#207] opened 2017-02-23 18:37 UTC
When trying to run the file `regression-example.jl` I get the following error.

```julia
julia> include("regression-example.jl")
WARNING: Method definition generate_inputs(Any, Any, Any) in module Main at /home/proy/.julia/v0.5/MXNet/examples/regression-example.jl:12 overwritten at /home/user/.julia/v0.5/MXNet/examples/regression-example.jl:12.
WARNING: Method definition output(Any) in module Main at /home/user/.julia/v0.5/MXNet/examples/regression-example.jl:13 overwritten at /home/user/.julia/v0.5/MXNet/examples/regression-example.jl:13.
LoadError: ------ MethodError --------------------- Stacktrace (most recent call last)

 [1] — include_from_node1(::String) at loading.jl:488

MethodError: MXNet.mx.#FullyConnected(::Array{Any,1}, ::MXNet.mx.#FullyConnected) is ambiguous. Candidates:
  (::MXNet.mx.#kw##FullyConnected)(::Array{Any,1}, ::MXNet.mx.#FullyConnected, args::MXNet.mx.SymbolicNode...)
  (::MXNet.mx.#kw##FullyConnected)(::Array{Any,1}, ::MXNet.mx.#FullyConnected, args::MXNet.mx.NDArray...)
while loading /home/user/.julia/v0.5/MXNet/examples/regression-example.jl, in expression starting on line 33
```

**Comment by mcreel** [comment] 2017-03-01 10:38
I have made a pull request that fixes this.

**Comment by pluskid** [comment] 2017-03-03 22:59
@mcreel Thanks for the PR!
@Balinus Closing this for now. Feel free to re-open if the issue is still not fixed.

**Closed by pluskid** 2017-03-03 22:59 UTC

**Comment by Balinus** [comment] 2017-03-06 14:21
It does work now. Thanks!
