### ISSUE TITLE
Problems with workspace size

### ISSUE THREAD

**Issue by vchuravy** [dmlc/MXNet.jl#14] opened 2015-11-03 09:32 UTC
I am running into an issue that reconstructing a network and running it for prediction fails with a workspace error.

The network architecture looks like this:
````julia
using MXNet

function create_conv(data, filters; kernel = (3, 3), pad=(1, 1), stride=(1,1))
  conv = @mx.chain mx.Convolution(data=data,
                                  kernel=kernel,
                                  num_filter=filters,
                                  pad=pad,
                                  stride=stride,
                                  workspace = 2300)  =>
                   mx.Activation(act_type=:relu)
end

function create_network()
  # Create network structure
  # Fully convolutional network
  data = mx.Variable(:data)
  conv1 = create_conv(data, 64)
  conv2 = create_conv(conv1, 128)
  conv3 = create_conv(conv2, 128)
  pool1 = mx.Pooling(data = conv3, kernel = (2,2), pool_type = (:max), stride = (2,2))
  conv4 = create_conv(pool1, 256)
  conv5 = create_conv(conv4, 512)
  conv6 = create_conv(conv5, 512)
  conv7 = create_conv(conv6, 2, pad = (0,0), kernel = (1, 1))
  deconv = mx.Deconvolution(data = conv7, num_filter = 2, kernel = (2,2), stride = (2,2))
  net = mx.SoftmaxOutput(data=deconv, name=:softmax, multi_output = true)
end
````

and predictions looks like this

````julia
using HDF5
using MXNet

function load_test(filename)
  fid = h5open(filename, "r")

  data = readmmap(fid["data"])

  close(fid)
  mx.ArrayDataProvider(data, batch_size = 10)
end

prefix = "..."
model_epoch = 4

model = mx.load_checkpoint("..:", model_epoch, mx.FeedForward)

  data = load_test("test.h5")
  pred = mx.predict(model, data)
````

Using a workspace of `2300`
````julia
[18:23:45] ./dmlc-core/include/dmlc/logging.h:208: [18:23:45] src/operator/./convolution-inl.h:252: Check failed: (param_.workspace) >= (scol.Size() + sdst.Size()) 
Minimum workspace size: 605491200
Given: 602931200
[18:23:45] ./dmlc-core/include/dmlc/logging.h:208: [18:23:45] src/engine/./threaded_engine.h:295: [18:23:45] src/operator/./convolution-inl.h:252: Check failed: (param_.workspace) >= (scol.Si
ze() + sdst.Size())                                                                                                                                                                            Minimum workspace size: 605491200
Given: 602931200
terminate called after throwing an instance of 'dmlc::Error'
  what():  [18:23:45] src/engine/./threaded_engine.h:295: [18:23:45] src/operator/./convolution-inl.h:252: Check failed: (param_.workspace) >= (scol.Size() + sdst.Size()) 
Minimum workspace size: 605491200
Given: 602931200
```

So I tried changing the workspace size by changing the values in `symbol.json`

Using a workspace size of `3072`
```julia
[18:31:08] ./dmlc-core/include/dmlc/logging.h:208: [18:31:08] src/operator/./convolution-inl.h:252: Check failed: (param_.workspace) >= (scol.Size() + sdst.Size()) 
Minimum workspace size: 875888640
Given: 805306368
[18:31:08] ./dmlc-core/include/dmlc/logging.h:208: [18:31:08] src/engine/./threaded_engine.h:295: [18:31:08] src/operator/./convolution-inl.h:252: Check failed: (param_.workspace) >= (scol.Si
ze() + sdst.Size())                                                                                                                                                                            Minimum workspace size: 875888640
Given: 805306368
terminate called after throwing an instance of 'dmlc::Error'
  what():  [18:31:08] src/engine/./threaded_engine.h:295: [18:31:08] src/operator/./convolution-inl.h:252: Check failed: (param_.workspace) >= (scol.Size() + sdst.Size()) 
Minimum workspace size: 875888640
Given: 805306368
```

**Comment by pluskid** [comment] 2015-11-03 12:26
@tqchen @antinucleon Any idea what might be potentially causing this kind of error?

**Comment by vchuravy** [comment] 2015-11-03 13:01
I saw this: https://github.com/dmlc/mxnet/issues/212, but I am running it on a CPU.

**Comment by pluskid** [comment] 2015-11-03 14:28
@vchuravy Did you do everything on CPU or training on GPU but predict on CPU? Is it possible that the batch size is smaller in training data so that the workspace size is not enough for testing?

**Comment by vchuravy** [comment] 2015-11-03 14:48
Both training and prediction are happening on the CPU and the batch size is the same.

What I find weird is the change of
```
Minimum workspace size: 605491200
Given: 602931200
```
to
```
Minimum workspace size: 875888640
Given: 805306368
```

so even when I give MXNet more workspace to work with, it still wants more.

**Comment by vchuravy** [comment] 2015-11-05 09:04
@antinucleon You introduced the check that is failing for me, any ideas?

**Comment by antinucleon** [comment] 2015-11-05 16:09
Hi Valentin,

Sorry I was super busy yesterday. I will take a look sometime today. It
looks strange and I will translate into Python side to see how whether I
can reproduce this problem.

**Comment by vchuravy** [comment] 2015-11-05 16:14
Thanks, fyi the input size is `(384, 216, 1, 10)`.

**Comment by antinucleon** [comment] 2015-11-05 16:46
Sorry there is a gap between memory layout in Julia and Python. Could you tell me batch/channel/h/w of input?

**Comment by tqchen** [comment] 2015-11-05 17:19
It is reversed, as (w, h, c, batch)

**Comment by vchuravy** [comment] 2015-11-09 03:15
@pluskid 
If I run my code with MXNet.jl at the current master instead of `0.0.3` I get the following and I have not yet been able to find track down the where the difference comes from.

````
[12:13:31] ./dmlc-core/include/dmlc/logging.h:208: [12:13:31] src/operator/./convolution-inl.h:297: Check failed: (dshape.ndim()) == (4) Input data should be 4D in batch-num_filter-y-x
ERROR: LoadError: MXNet.mx.MXError("[12:13:31] src/operator/./convolution-inl.h:297: Check failed: (dshape.ndim()) == (4) Input data should be 4D in batch-num_filter-y-x")
 [inlined code] from /home/v/valentin-churavy/.julia/v0.4/MXNet/src/base.jl:57
 in __infer_shape#2__ at /home/v/valentin-churavy/.julia/v0.4/MXNet/src/symbol.jl:56
 in simple_bind at /home/v/valentin-churavy/.julia/v0.4/MXNet/src/executor.jl:132
 in _setup_predictor at /home/v/valentin-churavy/.julia/v0.4/MXNet/src/model.jl:131
 in predict at /home/v/valentin-churavy/.julia/v0.4/MXNet/src/model.jl:183
 [inlined code] from /home/v/valentin-churavy/bees/bee_tools/src/pixel/test.jl:47
 in anonymous at no file:46
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/v/valentin-churavy/bees/bee_tools/src/pixel/test.jl, in expression starting on line 45
````

The data source is `...[:data],Array{Float32,N}[],Symbol[],10,100,false,0.0f0,0.0f0,[mx.NDArray(384,216,1,10)],MXNet.mx.NDArray[])`

**Comment by vchuravy** [comment] 2015-11-09 04:17
It looks like it drops the singleton dimensions

````
(gdb) p dshape.ndim() 
$1 = 2 
````

**Comment by pluskid** [comment] 2015-11-09 04:22
Hmm... Can you try MXNet.jl 0.0.3 again? Just to make sure it is due to changes in the Julia side or cpp side.

**Comment by vchuravy** [comment] 2015-11-09 04:55
So I think I found the issue (for that at least)

The array I give to MXNet has `size(data) = (384,216,1,100)`

But the size of the array that the `MXNet.mx.ArrayDataProvider` is holding is `size(datap.data_arrays[1]) (82944,100)`

This seems to stem from https://github.com/dmlc/MXNet.jl/blame/master/src/io.jl#L386 and that maybe the 2D-tensor is not turned back into a 4D tensor?

````
fid = h5open(filename, "r")
data = readmmap(fid["data"])
@show size(data)
mx.ArrayDataProvider(data, batch_size = 10)
````

**Comment by pluskid** [comment] 2015-11-09 05:31
@vchuravy Yes, that data is reshaped for convenience, but each mini-batch should have correct shape. Otherwise the unit-test should not pass. You could verify that by something like this:
```julia
for batch in provider
  for d in mx.get_data(provider, batch)
    println(size(d))
  end
  break
end
```
Let me know if the printed size is not correct.

**Comment by vchuravy** [comment] 2015-11-09 05:45
That reports the correct mini_batch size, but the shape that gets passed to the convolution operator is 
````
(gdb) p dshape
$5 = (const mxnet::TShape &) @0x1eb8bf0: {static kStackCache = 4, ndim_ = 2, num_heap_allocated_ = 0, data_stack_ = {100, 82944, 38902976, 0}, 
  data_heap_ = 0x0}

(gdb) p dshape[0]
$6 = (mshadow::index_t &) @0x1eb8bf8: 100

(gdb) p dshape[1]
$7 = (mshadow::index_t &) @0x1eb8bfc: 82944
````

Where 100 is the number of samples I have.

**Comment by pluskid** [comment] 2015-11-09 05:48
@vchuravy I see, there is a bug in reporting the shape! I will fix it now!

**Comment by pluskid** [comment] 2015-11-09 05:51
@vchuravy Should be fixed now. Can you test? Thanks!

**Comment by vchuravy** [comment] 2015-11-09 05:53
Thanks that seems to fix it and I also don't get the workspace error anymore!

**Comment by vchuravy** [comment] 2015-11-09 06:59
@pluskid Maybe time to tag a new release?

**Comment by vchuravy** [comment] 2015-11-12 05:56
@antinucleon I am seeing the same thing now during training if I remove the pooling and deconvolution layers.

````
[14:37:15] ./dmlc-core/include/dmlc/logging.h:208: [14:37:15] src/engine/./threaded_engine.h:295: [14:37:15] src/operator/./convolution-inl.h:252: Check failed: (param_.workspace) >= (scol.Si
ze() + sdst.Size()) 
Minimum workspace size: 700710912
Given: 602931200
terminate called after throwing an instance of 'dmlc::Error'
  what():  [14:37:15] src/engine/./threaded_engine.h:295: [14:37:15] src/operator/./convolution-inl.h:252: Check failed: (param_.workspace) >= (scol.Size() + sdst.Size()) 
Minimum workspace size: 700710912
Given: 602931200
````

After increasing the workspace size to 3072
````
Minimum workspace size: 934281216
Given: 805306368
````

**Comment by vchuravy** [comment] 2015-11-13 06:03
@antinucleon 

The problem occurs when `nstep_`
https://github.com/dmlc/mxnet/blob/6db1aae163113ddc622a9b75e12659307097248f/src/operator/convolution-inl.h#L243

equals `nstep_` https://github.com/dmlc/mxnet/blob/6db1aae163113ddc622a9b75e12659307097248f/src/operator/convolution-inl.h#L246

**Closed** 2015-11-18 00:12 UTC
