### ISSUE TITLE
Examples won't run in Julia v0.6

### ISSUE THREAD

**Issue by SimonEnsemble** [dmlc/MXNet.jl#286] opened 2017-10-01 21:04 UTC
Julia v0.6
Ubuntu 16.05
[Latest from `Pkg.add("MXNet")`. But `Pkg.checkout("MXNnet")` gives: `ERROR: MXNet is dirty, bailing`...]

In `MXNet/examples/mnist/`:

`julia lenet.jl` yields:

```
ERROR: LoadError: MethodError: MXNet.mx.#Activation(::Array{Any,1}, ::MXNet.mx.#Activation) is ambiguous. Candidates:
  (::MXNet.mx.#kw##Activation)(::Array{Any,1}, ::MXNet.mx.#Activation, args::MXNet.mx.SymbolicNode...) in MXNet.mx
  (::MXNet.mx.#kw##Activation)(::Array{Any,1}, ::MXNet.mx.#Activation, args::MXNet.mx.NDArray...) in MXNet.mx
Possible fix, define
  (::MXNet.mx.#kw##Activation)(::Array{Any,1}, ::MXNet.mx.#Activation)
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:569
 [2] include(::String) at ./sysimg.jl:14
 [3] process_options(::Base.JLOptions) at ./client.jl:305
 [4] _start() at ./client.jl:371
while loading /home/cokes/.julia/v0.6/MXNet/examples/mnist/lenet.jl, in expression starting on line 10
```

What needs to be changed? Once I learn how, I can update the other examples.

**Comment by iblis17** [comment] 2017-10-02 01:09
hi @SimonEnsemble ,
I'm on 6d1ba5338c381176ff22e9940430fdcae52c6b52 and Julia 0.6, but cannot reproduce your error.

The error indicate that you have modified file(s) in the working directory (usually `~/.julia/v0.6/MXNet`). `Pkg`(git) reject to checkout master.
```
ERROR: MXNet is dirty, bailing
```

**Comment by SimonEnsemble** [comment] 2017-10-02 02:01
When I installed MXNet.jl on Ubuntu, I got the following error upon `Pkg.build(MXNet)`:
```
LoadError: failed process: Process(`git submodule update --init`, ProcessExited(1))
```

I then used your solution [here](https://github.com/dmlc/MXNet.jl/issues/263), commenting out the line `git submodule update --init` in `build.jl`, and it built successfully. Could this be the reason I got errors after running the examples?

I deleted MXNet.jl, then `Pkg.checkout(MXNet)` successfully. Now I get a different error upon `Pkg.build(MXNet)`:

```
LoadError: TypeError: anonymous: in ccall: first argument not a pointer or valid constant expression, expected Ptr, got Tuple{Symbol,String}
while loading /home/cokes/.julia/v0.6/MXNet/deps/build.jl, in expression starting on line 53
```

**Comment by SimonEnsemble** [comment] 2017-10-02 02:10
Even the most basic example from the README will not run after a simple `Pkg.add(MXNet)`, comment out `git submodule update --init` in `build.jl`, and `Pkg.build(MXNet)`:

```
using MXNet

mlp = @mx.chain mx.Variable(:data)             =>
  mx.FullyConnected(name=:fc1, num_hidden=128) =>
  mx.Activation(name=:relu1, act_type=:relu)   =>
  mx.FullyConnected(name=:fc2, num_hidden=64)  =>
  mx.Activation(name=:relu2, act_type=:relu)   =>
  mx.FullyConnected(name=:fc3, num_hidden=10)  =>
  mx.SoftmaxOutput(name=:softmax)
```

gives

```
ERROR: MethodError: MXNet.mx.#FullyConnected(::Array{Any,1}, ::MXNet.mx.#FullyConnected) is ambiguous. Candidates:
  (::MXNet.mx.#kw##FullyConnected)(::Array{Any,1}, ::MXNet.mx.#FullyConnected, args::MXNet.mx.SymbolicNode...) in MXNet.mx
  (::MXNet.mx.#kw##FullyConnected)(::Array{Any,1}, ::MXNet.mx.#FullyConnected, args::MXNet.mx.NDArray...) in MXNet.mx
Possible fix, define
  (::MXNet.mx.#kw##FullyConnected)(::Array{Any,1}, ::MXNet.mx.#FullyConnected)
```

**Comment by SimonEnsemble** [comment] 2017-10-02 02:17
I should give a full output of the build error:

```
Cloning into 'ps-lite'...
remote: Counting objects: 1910, done.
remote: Total 1910 (delta 0), reused 0 (delta 0), pack-reused 1910
Receiving objects: 100% (1910/1910), 581.49 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1217/1217), done.
Checking connectivity... done.
INFO: Changing Directory to /home/cokes/.julia/v0.6/MXNet/deps/src/mxnet
INFO: Changing Directory to /home/cokes/.julia/v0.6/MXNet/deps/src/mxnet
INFO: Changing Directory to /home/cokes/.julia/v0.6/MXNet/deps/src/mxnet
warning: unable to rmdir dlpack: Directory not empty
Note: checking out 'v0.10.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 8713d25... [R][DOC] update R installation guide (#6457)
INFO: Changing Directory to /home/cokes/.julia/v0.6/MXNet/deps/src/mxnet
fatal: reference is not a tree: 89de7ab20167909bc2c4f8acd397671c47cf3c0d
Unable to checkout '89de7ab20167909bc2c4f8acd397671c47cf3c0d' in submodule path 'cub'
======================================================================================[ ERROR: MXNet ]======================================================================================

LoadError: failed process: Process(`git submodule update --init`, ProcessExited(1)) [1]
while loading /home/cokes/.julia/v0.6/MXNet/deps/build.jl, in expression starting on line 58
```

**Comment by iblis17** [comment] 2017-10-02 03:07
I think you need to do manually `git pull` in `~/.julia/v0.6/MXNet/deps/src/mxnet`
Could you check your repo version of upstream mxnet?

**Comment by SimonEnsemble** [comment] 2017-10-02 03:12
`git checkout 6d1ba53`, `Pkg.build("MXNet")` leads to same `ccall` error above.
The git checkout says:
```
Previous HEAD position was 643b8d4... Merge pull request #251 from dmlc/vc/v0.2.3
HEAD is now at 6d1ba53... Merge pull request #279 from iblis17/sym-reshape
```

**Comment by iblis17** [comment] 2017-10-02 03:14
hmm MXNet.jl (`~/.julia/v0.6/MXNet`) and upstream mxnet (`~/.julia/v0.6/MXNet/deps/src/mxnet`) are different repoes
so... what is your upstream mxnet version?

**Comment by SimonEnsemble** [comment] 2017-10-02 03:20
I see... In `~/.julia/v0.6/MXNet/deps/src/mxnet`, if I `git status`, I get:
```
HEAD detached at v0.10.0
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

	modified:   cub (new commits)
	modified:   nnvm (modified content)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	dlpack/

no changes added to commit (use "git add" and/or "git commit -a")
```
Is this the information you are looking for?

**Comment by iblis17** [comment] 2017-10-02 03:22
yeah, hope updating upsteam mxnet and recompiling helps for your issue

**Comment by SimonEnsemble** [comment] 2017-10-02 03:31
I successfully `git pull origin master` inside `~/.julia/v0.6/MXNet/deps/src/mxnet` and still got, upon `Pkg.build("MXNet")`:

```
LoadError: TypeError: anonymous: in ccall: first argument not a pointer or valid constant expression, expected Ptr, got Tuple{Symbol,String}
while loading /home/cokes/.julia/v0.6/MXNet/deps/build.jl, in expression starting on line 53
```

**Comment by iblis17** [comment] 2017-10-02 03:41
oh, my bad: workaround 
```
diff --git a/deps/build.jl b/deps/build.jl
index b8ea163..0583554 100644
--- a/deps/build.jl
+++ b/deps/build.jl
@@ -55,7 +55,7 @@ if HAS_CUDA  # then check cudnn
     HAS_CUDNN = !isempty(cudnnlib) && Libdl.dlopen_e(cudnnlib) != C_NULL
     if HAS_CUDNN
       # TODO: do more version check?
-      cudnnver = dec(ccall((:cudnnGetVersion, cudnnlib), Csize_t, ()))
+      #= cudnnver = dec(ccall((:cudnnGetVersion, cudnnlib), Csize_t, ())) =#
     end
   end
 end
```

I'm investigating on a better solution

**Comment by iblis17** [comment] 2017-10-02 03:47
and build with GPU support is still painful.
FYI: https://github.com/dmlc/MXNet.jl/pull/275#issuecomment-328890217

**Comment by SimonEnsemble** [comment] 2017-10-02 04:05
Looks like now it can't find `cuda.h` during the step:
```
make -j8 USE_BLAS=openblas 'MSHADOW_LDFLAGS=-lm /home/cokes/juliav0.6/bin/../lib/julia/libopenblas64_.so
```

My CUDA path is `/usr/local/cuda-8.0/lib64` and cudaNN is `/home/cokes/cudaNN/lib64`.
I added to the build script:
`push!(CUDAPATHS, "/usr/local/cuda-8.0/lib64")` but still couldn't find `cuda.h`.

**Comment by iblis17** [comment] 2017-10-02 04:54
please set your CUDA_HOME (http://dmlc.ml/MXNet.jl/latest/user-guide/install/)
```julia
julia> ENV["CUDA_HOME"] = "..."

julia> Pkg.build("MXNet")
```

**Comment by iblis17** [comment] 2017-10-02 07:13
@vchuravy should we switch to cmake for upstream mxnet and leave cmake doing all the work?

**Comment by vchuravy** [comment] 2017-10-02 15:06
If upstream is moving towards cmake then yes switching would be good, especially if it means that we can reduce the logic in build.jl

**Comment by iblis17** [comment] 2017-10-02 16:35
> If upstream is moving towards cmake

Not sure which way is recommanded, since I cannot find any related statement in doc.

 I just tried cmake. CUDA detection looks fine, seems it leverages the CUDA finder shipped with cmake

**Comment by pluskid** [comment] 2017-10-08 12:07
Last time I checked (a few months ago) the upstream is sticking with Makefiles but there are contributors who actively maintain a cmake version.

**Comment by iblis17** [comment] 2017-10-25 12:31
close this now?

**Comment by SimonEnsemble** [comment] 2017-10-25 17:18
@iblis17 still, when I install the latest version of MXNet from their website and follow their instructions, allowing MXNet.jl to automatically detect my installation (which it does), I get the following error from the example on the README:

```
using MXNet
mlp = @mx.chain mx.Variable(:data)             =>
         mx.FullyConnected(name=:fc1, num_hidden=128) =>
         mx.Activation(name=:relu1, act_type=:relu)   =>
         mx.FullyConnected(name=:fc2, num_hidden=64)  =>
         mx.Activation(name=:relu2, act_type=:relu)   =>
         mx.FullyConnected(name=:fc3, num_hidden=10)  =>
         mx.SoftmaxOutput(name=:softmax)
```

```
ERROR: MethodError: MXNet.mx.#FullyConnected(::Array{Any,1}, ::MXNet.mx.#FullyConnected) is ambiguous. Candidates:
  (::MXNet.mx.#kw##FullyConnected)(::Array{Any,1}, ::MXNet.mx.#FullyConnected, args::MXNet.mx.SymbolicNode...) in MXNet.mx
  (::MXNet.mx.#kw##FullyConnected)(::Array{Any,1}, ::MXNet.mx.#FullyConnected, args::MXNet.mx.NDArray...) in MXNet.mx
Possible fix, define
  (::MXNet.mx.#kw##FullyConnected)(::Array{Any,1}, ::MXNet.mx.#FullyConnected)
```

So this means we should change the directions on the README and suggest to NOT use an MXNet installation that is not installed automatically by MXNet.jl in the build script?

**Comment by iblis17** [comment] 2017-10-26 02:16
@SimonEnsemble well, maybe we should wait for upstream mxnet releasing the v0.12.0 (currently, it's in RC stage). Then, cut a release for MXNet.jl.

FYI: https://github.com/apache/incubator-mxnet/releases/tag/0.12.0.rc0

**Closed** 2017-11-13 18:17 UTC
